version: "1.0"

services:
  mongodb:
    image: mongo-iot-image:1.0
    container_name: mongo-client
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hepl
      - MONGO_INITDB_ROOT_PASSWORD=heplhepl
    ports:
      - "27017:27017"
